# Generated by Django 3.2.9 on 2022-01-02 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToDo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_date', models.TimeField()),
                ('text', models.CharField(max_length=200)),
            ],
        ),
    ]
